<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Restaurant [
<!ELEMENT Restaurant (Name, Restaurateur, Branch+)>
<!ELEMENT Restaurateur (Name, Contact) >
<!ELEMENT Branch (Address, MenuCard, Staff, Customer*, Table+, Area, Expenditure, Contact)>	
<!ELEMENT Address (Street, City, Pin, State, Country)>
<!ELEMENT Street (#PCDATA)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT Pin (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
 
<!ELEMENT MenuCard (Starter,MainCourse,Dessert)> 
<!ELEMENT Starter (Item+)>
<!ELEMENT MainCourse (Item+)>
<!ELEMENT Dessert (Item+)> 
 
<!ELEMENT Item ((Food|Beverage), Price, Origin?)> 
<!ATTLIST Item Id ID #REQUIRED>
<!ELEMENT Food (#PCDATA)>
<!ELEMENT Beverage (#PCDATA)>
<!ELEMENT Origin (#PCDATA)>
 
<!ELEMENT Staff (Manager+,Supervisor+,Chef+,Cashier+,Waiter+,Janitor+)>
<!ELEMENT Manager (Name, Salary, Contact)>
<!ELEMENT Supervisor (Name, Salary, Contact, ReportsTo)>
<!ELEMENT Chef (Name, WorksAt, Salary, Contact, ReportsTo)>
<!ELEMENT Cashier (Name, WorksAt, Salary, Contact, ReportsTo)>
<!ELEMENT Waiter (Name, WorksAt, Salary, Contact, ReportsTo*)>
<!ELEMENT Janitor (Name, WorksAt, Salary, Contact, ReportsTo*)>
<!ATTLIST Manager Id ID #REQUIRED>
<!ATTLIST Chef Id ID #REQUIRED>
<!ATTLIST Supervisor Id ID #REQUIRED>
<!ATTLIST Cashier Id ID #REQUIRED>
<!ATTLIST Waiter Id ID #REQUIRED>
<!ATTLIST Janitor Id ID #REQUIRED>
<!ELEMENT WorksAt EMPTY>
<!ATTLIST WorksAt areaId IDREF #REQUIRED>
<!ELEMENT Salary (#PCDATA)>
<!ELEMENT Contact (PhoneNo*, Email*)>
<!ELEMENT ReportsTo EMPTY>
<!ATTLIST ReportsTo staffId IDREF #REQUIRED>
 
<!ELEMENT Customer (Name, Contact?,Subscription?,Order)>
<!ATTLIST Customer Id ID #REQUIRED>
<!ELEMENT Subscription (Date,Duration,Details,Price)>
<!ELEMENT Duration (#PCDATA)>
<!ELEMENT Details (#PCDATA)>
<!ELEMENT Price (#PCDATA)>
 
<!ELEMENT Order (OrderedBy,Date,TableNo,OrderItem+,ServedBy,Amount)>
<!ATTLIST Order OrderNo ID #REQUIRED>
<!ELEMENT OrderedBy EMPTY>
<!ATTLIST OrderedBy customerId IDREF #REQUIRED>
<!ELEMENT Date (Day,Month,Year)>
<!ELEMENT Day (#PCDATA)>
<!ELEMENT Month (#PCDATA)>
<!ELEMENT Year (#PCDATA)>
<!ELEMENT TableNo EMPTY>
<!ATTLIST TableNo tableId IDREF #REQUIRED>
<!ELEMENT OrderItem EMPTY>
<!ATTLIST OrderItem itemId IDREF #REQUIRED>
<!ELEMENT ServedBy EMPTY>
<!ATTLIST ServedBy waiterId IDREF #REQUIRED>
<!ELEMENT Amount (#PCDATA)>
 
 
<!ELEMENT Table (TableStatus)>
<!ATTLIST Table Id ID #REQUIRED>
<!ELEMENT TableStatus (#PCDATA)>
 
<!ELEMENT Expenditure (#PCDATA)>
 
<!ELEMENT Area (Kitchen,BillingCounter,DiningArea,PartyHall+,RestRoom+,StorageRoom+)>
<!ELEMENT Kitchen (SurfaceArea)>
<!ELEMENT BillingCounter (SurfaceArea)>
<!ELEMENT DiningArea (SurfaceArea)>
<!ELEMENT PartyHall (SurfaceArea, BookedBy?)>
<!ELEMENT RestRoom (SurfaceArea)>
<!ELEMENT StorageRoom (SurfaceArea)>
<!ATTLIST Kitchen Id ID #REQUIRED>
<!ATTLIST BillingCounter Id ID #REQUIRED>
<!ATTLIST DiningArea Id ID #REQUIRED>
<!ATTLIST PartyHall Id ID #REQUIRED>
<!ATTLIST RestRoom Id ID #REQUIRED>
<!ATTLIST StorageRoom Id ID #REQUIRED>
<!ELEMENT BookedBy EMPTY>
<!ATTLIST BookedBy customerId IDREF #REQUIRED>
<!ELEMENT SurfaceArea (#PCDATA)> 

<!ELEMENT Name (#PCDATA)>
<!ELEMENT  PhoneNo (#PCDATA)>
<!ELEMENT  Email (#PCDATA)>
]>





<Restaurant>
    <Name>Vijayalankar</Name>
    <Restaurateur>
        <Name>Virat Shetty</Name>
        <Contact>
            <PhoneNo>8888000022</PhoneNo>
            <Email>ViratS@gmail.com</Email>
        </Contact>
    </Restaurateur>
    <Branch>
        <Address>
           <Street>Adyar Road</Street>
           <City>Chennai</City>
           <Pin>600015</Pin>
           <State>Tamil Nadu</State>
           <Country>India</Country>
        </Address>
        <MenuCard>
           <Starter>
               <Item Id = "I101">
                   <Food>Chilli Paneer</Food>
                   <Price>100</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I102">
                   <Food>Paneer 65</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I103">
                   <Food>Veg Manchurian</Food>
                   <Price>150</Price>
                   <Origin>China</Origin>
               </Item>
               <Item Id = "I104">
                   <Food>Veg Lollipop</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I105">
                   <Food>Chilli Potato</Food>
                   <Price>90</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I106">
                   <Food>Chicken Manchurian</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>         
               <Item Id = "I107">
                   <Food>Gobi Manchurian</Food>
                   <Price>110</Price>
                   <Origin>India</Origin>
               </Item>                                             
           </Starter>
           <MainCourse>
               <Item Id = "I108">
                   <Food>Hydrabadi Biryani</Food>
                   <Price>140</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I109">
                   <Food>Paneer Biryani</Food>
                   <Price>140</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I110">
                   <Food>Chicken Biryani</Food>
                   <Price>170</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I111">
                   <Food>Kashmiri Biryani</Food>
                   <Price>170</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I112">
                   <Food>Paneer Tikka Masala</Food>
                   <Price>110</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I113">
                   <Food>Butter Paneer Masala</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I114">
                   <Food>Kadhai Paneer</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I115">
                   <Food>Kashmiri Pulav</Food>
                   <Price>120</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I116">
                   <Food>Dal Khichadi</Food>
                   <Price>150</Price>
                   <Origin>India</Origin>
               </Item>
           </MainCourse>
           <Dessert>
               <Item Id = "I117">
                   <Food>Gulab Jamun</Food>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I118">
                   <Food>Ice Cream</Food>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I126">
                   <Food>Brownie</Food>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I119">
                   <Food>Ras Malai</Food>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I120">
                   <Beverage>Thumps Up</Beverage>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I121">
                   <Beverage>Coke</Beverage>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I122">
                   <Beverage>Chocolate Shake</Beverage>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I123">
                   <Beverage>Hot Chocolate</Beverage>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I124">
                   <Beverage>Milk</Beverage>
                   <Price>50</Price>
                   <Origin>India</Origin>
               </Item>
               <Item Id = "I125">
                   <Beverage>Strawberry Shake</Beverage>
                   <Price>70</Price>
                   <Origin>India</Origin>
               </Item>
           </Dessert>
       </MenuCard>
<Staff>
<Manager Id="S001">
                <Name>John</Name>
                <Salary>50000</Salary>
                <Contact>
                    <PhoneNo>9123456789</PhoneNo>
                    <Email>s002@gmail.com</Email>
                </Contact>
            </Manager>
            <Manager Id="S002">
                <Name>Tushar</Name>
                <Salary>50000</Salary>
                <Contact>
                    <PhoneNo>8123456789</PhoneNo>
                    <Email>s002@gmail.com</Email>
                </Contact>
            </Manager>

            <Supervisor Id="S003">
                <Name>Rupesh</Name>
                <Salary>30000</Salary>
                <Contact>
                    <PhoneNo>7123456789</PhoneNo>
                    <Email>s003@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
            </Supervisor>
            <Supervisor Id="S004">
                <Name>Rhythm</Name>
                <Salary>30000</Salary>
                <Contact>
                    <PhoneNo>7223456789</PhoneNo>
                    <Email>s004@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
            </Supervisor>
            <Supervisor Id="S005">
                <Name>Vansh</Name>
                <Salary>30000</Salary>
                <Contact>
                    <PhoneNo>7323456789</PhoneNo>
                    <Email>s005@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
            </Supervisor>
            <Supervisor Id="S006">
                <Name>Nitin</Name>
                <Salary>30000</Salary>
                <Contact>
                    <PhoneNo>7623456789</PhoneNo>
                    <Email>s006@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
            </Supervisor>
            <Supervisor Id="S007">
                <Name>Pranab</Name>
                <Salary>30000</Salary>
                <Contact>
                    <PhoneNo>6223456789</PhoneNo>
                    <Email>s004@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
            </Supervisor>


            <Chef Id="S008">
                <Name>Ajay</Name>
                <WorksAt areaId="A04"/>
                <Salary>25000</Salary>
                <Contact>
                    <PhoneNo>9123498765</PhoneNo>
                    <Email>s008@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
            </Chef>
            <Chef Id="S009">
                <Name>Shubham Rane</Name>
                <WorksAt areaId="A04"/>
                <Salary>25000</Salary>
                <Contact>
                    <PhoneNo>9123568765</PhoneNo>
                    <Email>s009@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
            </Chef>
            


            <Cashier Id="S010">
                <Name>Amol </Name>
                <WorksAt areaId="A03"/>
                <Salary>20000</Salary>
                <Contact>
                    <PhoneNo>8998755744</PhoneNo>
                    <Email>s010@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
            </Cashier>


            <Waiter Id="S011">
                <Name>Rakul</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8468755744</PhoneNo>
                    <Email>s011@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S003"/>
            </Waiter>
            <Waiter Id="S012">
                <Name>Rahul Sharma</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8434755744</PhoneNo>
                    <Email>s012@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S003"/>
            </Waiter>
            <Waiter Id="S013">
                <Name>Ramesh Dev</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8468755755</PhoneNo>
                    <Email>s013@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S003"/>
            </Waiter>
            <Waiter Id="S014">
                <Name>Shridhar Tambe</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8468789744</PhoneNo>
                    <Email>s014@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S004"/>
            </Waiter>
            <Waiter Id="S015">
                <Name>Pravin Tambe</Name>
                <WorksAt areaId="A15"/>
                <Salary>19000</Salary>
                <Contact>
                    <PhoneNo>8468789711</PhoneNo>
                    <Email>s015@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S004"/>
            </Waiter>
            <Waiter Id="S016">
                <Name>Manoj Kumar</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>5648789744</PhoneNo>
                    <Email>s016@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S004"/>
            </Waiter>
            <Waiter Id="S017">
                <Name>Shridhar Gupta</Name>
                <WorksAt areaId="A15"/>
                <Salary>17000</Salary>
                <Contact>
                    <PhoneNo>8568789744</PhoneNo>
                    <Email>s017@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S005"/>
            </Waiter>
            <Waiter Id="S018">
                <Name>Manoj Tambe</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8400000001</PhoneNo>
                    <Email>s018@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S005"/>
            </Waiter>
            <Waiter Id="S019">
                <Name>Ajay Rathod</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8400000002</PhoneNo>
                    <Email>s019@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S005"/>
            </Waiter>
            <Waiter Id="S020">
                <Name>Pratik Tiwari</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8400000003</PhoneNo>
                    <Email>s020@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S001"/>
                <ReportsTo staffId="S005"/>
            </Waiter>
            <Waiter Id="S021">
                <Name>Pradip Kumar</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8400000004</PhoneNo>
                    <Email>s021@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S006"/>
            </Waiter>
            <Waiter Id="S022">
                <Name>Pradip Patil</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8400000005</PhoneNo>
                    <Email>s022@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S006"/>
            </Waiter>
            <Waiter Id="S023">
                <Name>Shridhar Chaudhari</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>846878888</PhoneNo>
                    <Email>s023@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S006"/>
            </Waiter>
            <Waiter Id="S024">
                <Name>Kuldeep Tambe</Name>
                <WorksAt areaId="A15"/>
                <Salary>18500</Salary>
                <Contact>
                    <PhoneNo>777789744</PhoneNo>
                    <Email>s024@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S006"/>
            </Waiter>
            <Waiter Id="S025">
                <Name>Akash Patil</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8555789744</PhoneNo>
                    <Email>s025@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S006"/>
            </Waiter>
            <Waiter Id="S026">
                <Name>Tushar kamat</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>8468858744</PhoneNo>
                    <Email>s026@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S007"/>
            </Waiter>
            <Waiter Id="S027">
                <Name>Kumar Dev</Name>
                <WorksAt areaId="A15"/>
                <Salary>18000</Salary>
                <Contact>
                    <PhoneNo>5555589744</PhoneNo>
                    <Email>s027@gmail.com</Email>
                </Contact>
                <ReportsTo staffId="S002"/>
                <ReportsTo staffId="S007"/>
            </Waiter>
<Janitor Id="S028">
               <Name>Jayesh Ghorpade</Name>
               <WorksAt areaId="A04"/>
               <Salary>15000</Salary>
               <Contact>
                   <PhoneNo>9856321478</PhoneNo>
                   <Email>s028@gmail.com</Email>
               </Contact>
               <ReportsTo staffId="S001"/>
               <ReportsTo staffId="S005"/>
           </Janitor>
           <Janitor Id="S029">
               <Name>Shashikant Zine</Name>
               <WorksAt areaId="A04"/>
               <Salary>14000</Salary>
               <Contact>
                   <PhoneNo>9874563202</PhoneNo>
                   <Email>s029@gmail.com</Email>
               </Contact>
               <ReportsTo staffId="S001"/>
               <ReportsTo staffId="S006"/>
           </Janitor>
           <Janitor Id="S030">
               <Name>Suraj Shelke</Name>
               <WorksAt areaId="A15"/>
               <Salary>16000</Salary>
               <Contact>
                   <PhoneNo>8569321478</PhoneNo>
                   <Email>s030@gmail.com</Email>
               </Contact>
               <ReportsTo staffId="S001"/>
               <ReportsTo staffId="S006"/>
           </Janitor>
           <Janitor Id="S031">
               <Name>Tushar Unde</Name>
               <WorksAt areaId="A15"/>
               <Salary>16000</Salary>
               <Contact>
                   <PhoneNo>7458963214</PhoneNo>
                   <Email>s031@gmail.com</Email>
               </Contact>
               <ReportsTo staffId="S001"/>
               <ReportsTo staffId="S007"/>
           </Janitor>
           <Janitor Id="S032">
               <Name>Shubham Shingi</Name>
               <WorksAt areaId="A15"/>
               <Salary>16000</Salary>
               <Contact>
                   <PhoneNo>8855226963</PhoneNo>
                   <Email>s032@gmail.com</Email>
               </Contact>
               <ReportsTo staffId="S001"/>
               <ReportsTo staffId="S007"/>
           </Janitor>
        </Staff>
<Customer Id = "C00001">
            <Name>Rajesh Kumar</Name>
            <Contact>
                <PhoneNo>7077253526</PhoneNo>
                <Email>rajkum@gmail.com</Email>
            </Contact>
            <Subscription>
                <Date>
                    <Day>05</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <Duration>90</Duration>
                <Details> Quarterly </Details>
                <Price>300</Price>
            </Subscription>
            <Order OrderNo = "D100001">
                <OrderedBy customerId = "C00001"/>
                <Date>
                    <Day>20</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T12"/>
                <OrderItem itemId = "I103" />
    			<OrderItem itemId = "I120" />
    			<OrderItem itemId = "I111" />
                <ServedBy waiterId = "S011" />
                <Amount>252</Amount>
            </Order>
</Customer>

<Customer Id = "C00002">
            <Name>Ajay Kumar</Name>
            <Contact>
                <PhoneNo>7077254526</PhoneNo>
                <Email>ajakum@gmail.com</Email>
            </Contact>
            <Order OrderNo = "D100002">
                <OrderedBy customerId = "C00002"/>
                <Date>
                    <Day>20</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T07"/>
                <OrderItem itemId = "I113" />
    			<OrderItem itemId = "I107" />
    			<OrderItem itemId = "I106" />
                <ServedBy waiterId = "S012" />
                <Amount>153</Amount>
            </Order>
</Customer>

<Customer Id = "C00003">
            <Name>Mukesh Kumar</Name>
            <Contact>
                <PhoneNo>7077425963</PhoneNo>
                <Email>mukkum@gmail.com</Email>
            </Contact>
            <Subscription>
                <Date>
                    <Day>01</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <Duration>90</Duration>
                <Details> Quarterly </Details>
                <Price>300</Price>
            </Subscription>
            <Order OrderNo = "D100003">
                <OrderedBy customerId = "C00003"/>
                <Date>
                    <Day>20</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T02"/>
                <OrderItem itemId = "I107" />
    			<OrderItem itemId = "I117" />
    			<OrderItem itemId = "I120" />
                <ServedBy waiterId = "S013" />
                <Amount>100</Amount>
            </Order>
</Customer>

<Customer Id = "C00004">
            <Name>Lavi Junwal</Name>
            <Contact>
                <PhoneNo>8010254526</PhoneNo>
                <Email>lavjun@gmail.com</Email>
            </Contact>
            <Order OrderNo = "D100004">
                <OrderedBy customerId = "C00004"/>
                <Date>
                    <Day>20</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T04"/>
                <OrderItem itemId = "I113" />
    			<OrderItem itemId = "I122" />
    			<OrderItem itemId = "I106" />
                <ServedBy waiterId = "S014" />
                <Amount>341</Amount>
            </Order>
</Customer>

<Customer Id = "C00005">
            <Name>Karan Jaiswal</Name>
            <Contact>
                <PhoneNo>7077127469</PhoneNo>
                <Email>karjai@gmail.com</Email>
            </Contact>
            <Subscription>
                <Date>
                    <Day>01</Day>
                    <Month>February</Month>
                    <Year>2022</Year>
                </Date>
                <Duration>90</Duration>
                <Details> Quarterly </Details>
                <Price>300</Price>
            </Subscription>
            <Order OrderNo = "D100005">
                <OrderedBy customerId = "C00005"/>
                <Date>
                    <Day>21</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T01"/>
                <OrderItem itemId = "I103" />
    			<OrderItem itemId = "I119" />
    			<OrderItem itemId = "I101" />
                <ServedBy waiterId = "S014" />
                <Amount>286</Amount>
            </Order>
</Customer>

<Customer Id = "C00006">
            <Name>Ankit Gope</Name>
            <Contact>
                <PhoneNo>8120365956</PhoneNo>
                <Email>ankgop@gmail.com</Email>
            </Contact>
            <Order OrderNo = "D100006">
                <OrderedBy customerId = "C00006"/>
                <Date>
                    <Day>21</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T08"/>
                <OrderItem itemId = "I112" />
    			<OrderItem itemId = "I101" />
    			<OrderItem itemId = "I106" />
                <ServedBy waiterId = "S015" />
                <Amount>190</Amount>
            </Order>
</Customer>

<Customer Id = "C00007">
            <Name>Irshad Khan</Name>
            <Contact>
                <PhoneNo>7412365256</PhoneNo>
                <Email>irskha@gmail.com</Email>
            </Contact>
            <Subscription>
                <Date>
                    <Day>15</Day>
                    <Month>January</Month>
                    <Year>2022</Year>
                </Date>
                <Duration>365</Duration>
                <Details>Annual</Details>
                <Price>899</Price>
            </Subscription>
            <Order OrderNo = "D100007">
                <OrderedBy customerId = "C00007"/>
                <Date>
                    <Day>21</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T03"/>
                <OrderItem itemId = "I115" />
			    <OrderItem itemId = "I119" />
    			<OrderItem itemId = "I120" />
    			<OrderItem itemId = "I118" />
                <ServedBy waiterId = "S015" />
                <Amount>460</Amount>
            </Order>
</Customer>

<Customer Id = "C00008">
            <Name>Lalit Yadav</Name>
            <Contact>
                <PhoneNo>8010147963</PhoneNo>
                <Email>lalyad@gmail.com</Email>
            </Contact>
            <Order OrderNo = "D100008">
                <OrderedBy customerId = "C00008"/>
                <Date>
                    <Day>21</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>
                <TableNo tableId = "T09"/>
                <OrderItem itemId = "I112" />
			    <OrderItem itemId = "I102" />
                <ServedBy waiterId = "S019" />
                <Amount>160</Amount>
            </Order>
</Customer>

<Customer Id = "C00009">
            <Name>Ganesh Karnam</Name>
            <Contact>
                <PhoneNo>7625963258</PhoneNo>
                <Email>gankar@gmail.com</Email>
            </Contact>
            <Subscription>
                <Date>
                    <Day>01</Day>
                    <Month>January</Month>
                    <Year>2022</Year>
                </Date>
                <Duration>90</Duration>
                <Details>Quarterly</Details>
                <Price>300</Price>
            </Subscription>
            <Order OrderNo = "D100009">
                <OrderedBy customerId = "C00009"/>
                <Date>
                    <Day>21</Day>
                    <Month>March</Month>
                    <Year>2022</Year>
                </Date>